# Generated by Django 2.2 on 2020-02-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_problemreported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreported',
            options={'verbose_name': 'Problem Report', 'verbose_name_plural': 'Problems Reports'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='procution_line',
            new_name='production_line',
        ),
    ]
