# Generated by Django 2.2 on 2020-02-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
